ignore:
  - "src/AthenaBackend.Infrastructure/Migrations/**/*" 
  - "src/AthenaBackend.Infrastructure/ReadModel/**/*map.cs" 
  - "src/AthenaBackend.Infrastructure/WriteModel/**/*map.cs" 
  - "src/AthenaBackend.Infrastructure/Migrations/*" 