version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "src/AthenaBackend.WebApi/AthenaBackend.WebApi.csproj" }}
            - dotnet-packages-v1-{{ checksum "src/AthenaBackend.Domain/AthenaBackend.Domain.csproj" }}
            - dotnet-packages-v1-{{ checksum "src/AthenaBackend.Infrastructure/AthenaBackend.Infrastructure.csproj" }}
            - dotnet-packages-v1-{{ checksum "src/AthenaBackend.Application/AthenaBackend.Application.csproj" }}
            - dotnet-packages-v1-{{ checksum "src/AthenaBackend.Common/AthenaBackend.Common.csproj" }}
            - dotnet-packages-v1-{{ checksum "test/AthenaBackend.DomainTest/AthenaBackend.DomainTest.csproj" }}
            - dotnet-packages-v1-{{ checksum "test/AthenaBackend.ApplicationTest/AthenaBackend.ApplicationTest.csproj" }}
            - dotnet-packages-v1-{{ checksum "test/AthenaBackend.CommonTest/AthenaBackend.CommonTest.csproj" }}
            - dotnet-packages-v1-{{ checksum "test/AthenaBackend.InfrastructureTest/AthenaBackend.InfrastructureTest.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore ~/src/AthenaBackend.WebApi/AthenaBackend.WebApi.csproj

      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "src/AthenaBackend.WebApi/AthenaBackend.WebApi.csproj" }}
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "src/AthenaBackend.Domain/AthenaBackend.Domain.csproj" }}
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "src/AthenaBackend.Infrastructure/AthenaBackend.Infrastructure.csproj" }}
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "src/AthenaBackend.Application/AthenaBackend.Application.csproj" }}
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "src/AthenaBackend.Common/AthenaBackend.Common.csproj" }}
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "test/AthenaBackend.DomainTest/AthenaBackend.DomainTest.csproj" }}
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "test/AthenaBackend.ApplicationTest/AthenaBackend.ApplicationTest.csproj" }}
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "test/AthenaBackend.CommonTest/AthenaBackend.CommonTest.csproj" }}
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "test/AthenaBackend.InfrastructureTest/AthenaBackend.InfrastructureTest.csproj" }}

      - run:
          name: "Print Working Directory"
          command: pwd
      
      - run:
          name: "Run Common Tests"
          command: dotnet.exe test test/AthenaBackend.CommonTest/AthenaBackend.CommonTest.csproj  -v n --results-directory:test\test_coverage --collect:"Code Coverage"
      - run:
          name: "Run Domain Tests"
          command: dotnet.exe test test/AthenaBackend.DomainTest/AthenaBackend.DomainTest.csproj  -v n --results-directory:test\test_coverage --collect:"Code Coverage"
      - run:
          name: "Run Infrastructure Tests"
          command: dotnet.exe test test/AthenaBackend.InfrastructureTest/AthenaBackend.InfrastructureTest.csproj  -v n --results-directory:test\test_coverage --collect:"Code Coverage"
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test test/AthenaBackend.ApplicationTest/AthenaBackend.ApplicationTest.csproj  -v n --results-directory:test\test_coverage --collect:"Code Coverage"
      
      - run:
          name: "Print Working Directory"
          command: pwd
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build "src/AthenaBackend.WebApi/AthenaBackend.WebApi.csproj" --configuration Release
workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test